import { GoogleGenAI } from "@google/genai";

// Initialize Gemini Client
const getClient = () => {
  const apiKey = process.env.API_KEY;
  if (!apiKey) {
    throw new Error("API Key not found in environment variables");
  }
  return new GoogleGenAI({ apiKey });
};

// Helper to clean base64 string
const cleanBase64 = (data: string) => {
  return data.replace(/^data:image\/(png|jpeg|jpg|webp);base64,/, "");
};

/**
 * Generate clothing using Nano Banana (gemini-2.5-flash-image)
 */
export const generateClothingImage = async (prompt: string): Promise<string> => {
  const ai = getClient();
  const fullPrompt = `A high-quality, professional product photography shot of ${prompt}. The clothing should be displayed on a neutral background or a mannequin, suitable for fashion design reference. Flat lay or front view.`;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image', // Fast image generation
      contents: { parts: [{ text: fullPrompt }] },
      config: {
        imageConfig: {
          aspectRatio: "3:4"
        }
      }
    });

    // Extract image from response
    let base64Image = "";
    if (response.candidates?.[0]?.content?.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          base64Image = part.inlineData.data;
          break;
        }
      }
    }

    if (!base64Image) {
      throw new Error("No image generated by the model.");
    }

    return `data:image/png;base64,${base64Image}`;
  } catch (error) {
    console.error("Clothing generation error:", error);
    throw error;
  }
};

/**
 * Perform Virtual Try-On using Nano Banana (gemini-2.5-flash-image)
 * Switched from Pro to Flash to meet user requirement and fix permission errors.
 */
export const generateTryOn = async (faceImageBase64: string, clothImageBase64: string): Promise<string> => {
  const ai = getClient();

  // Clean base64 headers
  const faceData = cleanBase64(faceImageBase64);
  const clothData = cleanBase64(clothImageBase64);

  // Prompt engineering for virtual try-on with Flash Image
  const prompt = `
    Generate a photorealistic full-body portrait.
    Use the person from the first image and dress them in the clothing from the second image.
    Ensure the clothing fits naturally on the body.
    High quality fashion photography, full body shot.
    Maintain the identity of the person.
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image', // User requested Nano Banana
      contents: {
        parts: [
          { text: prompt },
          {
            inlineData: {
              mimeType: 'image/jpeg',
              data: faceData
            }
          },
          {
            inlineData: {
              mimeType: 'image/jpeg',
              data: clothData
            }
          }
        ]
      },
      config: {
        imageConfig: {
          aspectRatio: "3:4" // Portrait ratio
          // imageSize is NOT supported for flash-image, so we remove it.
        }
      }
    });

    let resultBase64 = "";
    if (response.candidates?.[0]?.content?.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          resultBase64 = part.inlineData.data;
          break;
        }
      }
    }

    if (!resultBase64) {
      throw new Error("Failed to generate try-on result.");
    }

    return `data:image/png;base64,${resultBase64}`;
  } catch (error) {
    console.error("Try-on generation error:", error);
    throw error;
  }
};

// Helper utility to convert file to base64
export const fileToBase64 = (file: File): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => resolve(reader.result as string);
    reader.onerror = (error) => reject(error);
  });
};

// Helper to fetch preset URL and convert to base64 for API usage
export const urlToBase64 = async (url: string): Promise<string> => {
  try {
    const response = await fetch(url);
    const blob = await response.blob();
    return await fileToBase64(blob as File);
  } catch (e) {
    console.error("Error converting URL to base64", e);
    return "";
  }
};